### ISSUE TITLE
Expand backend code to handle more generic layer

### ISSUE THREAD

**Issue by viviant100** [podaac/gibs-imagestat#4]
Currently the test dataset is hard-coded to MUR SST.  The task is to update the backend service to work with any layer in GIBS, in addition to MUR layer. 

The work involves getting a query link from the frontend (worldview) to query datasets from GIBS, compute the statistics on the backend, and then send back the query to the worldview.

**Comment by vaishnaviyathirajam** [comment]
[http://ec2-52-13-63-64.us-west-2.compute.amazonaws.com:8080/get_stats_oiip_dag?lon_min=-50.992&lat_min[…]on&analysisName=spatial_summary_statistics](http://ec2-52-13-63-64.us-west-2.compute.amazonaws.com:8080/get_stats_oiip_dag?lon_min=-50.992&lat_min=13.672&lon_max=-37.013&lat_max=19.590&time_min=2019-03-02&time_max=2019-03-02&datasetName=JPL-CHL25-fv03_ChlorophyllAconcentration&colormapurl=https://oiip.jpl.nasa.gov/colormaps/JPL-CHL25-fv03.xml&format=json&analysisName=spatial_summary_statistics)

**Comment by viviant100** [comment]
@vaishnaviyathirajam to PR the updated code
